### ISSUE TITLE
TypeError: bpy_prop_collaction[key]: invalid key, must be a string or an int, not NoneType

### ISSUE THREAD

**Issue by Schaggo** [pKrime/pyqt_snippets#1]
Hi!

I stumbled upon your script while trying to convert a non-human character rigged with rigify for Unity.
Upon hitting "Make Game Friendly" I encounter the error : 

``TypeError: bpy_prop_collaction[key]: invalid key, must be a string or an int, not NoneType``

Any hint, what might cause the problem?

Blender 2.9
macOS Catalina

**Comment by Schaggo** [comment]
After testing it seems, the error can be ignored. 
Sorry, for the fuzz...

**Comment by pKrime** [comment]
Hi Schaggo,

actually you are right, the bird rig is not processed correctly. That error happens only at the end of the script, after it has managed to unify the DEF hierarchy, so I guess you can export that rig to unity.

There are two minor issues:

- The def rig is not brought under the "root" bone, so you will find some "MCH" bones in the exported hierarchy
- The tail is still the origin of the deformation hierarchy, that will make animating in Unity difficult

I will sort those issues as soon as I can, thanks for reporting, as I hadn't tried the bird rig yet

Cheers!

P.S. no error can be ignored! :)

**Comment by Schaggo** [comment]
Thanks for being so thorough! 
I am actually using the cat rig, if that helps.

**Comment by pKrime** [comment]
please have a try with the latest version: I have pushed some fixes
