### ISSUE TITLE
Eyes not transfered

### ISSUE THREAD

**Issue by ghost** [pKrime/pyqt_snippets#2]
I'm using blender 2.92 with latest rigify and eyes are not defined by a Def prefixed bone. So they arent transfer into the new rig. Any fix ?

**Comment by pKrime** [comment]
Hi,

I have transferred this snippet to a new addon

https://github.com/pKrime/Charigty-Scripts

To convert the rig hierarchy, in pose mode, right clic on the viewport to display a context menu, then choose "Rigify Game Friendly"

I have added an option to transfer the eyes, enabled by default

Cheers!
